### PR TITLE
Added port range check when adding neighnat entry

### PR DESCRIPTION
**Pull request by byteocean**
Added overlapping port range checking when adding neighnat entries.

### CODE REVIEW

**Review by guvenc — APPROVED** [review]
Looks good to me.

**Comment by guvenc** [comment]
@byteocean  could you please rebase ? seems to be conflicting with main branch now. Thanks.

**Comment by PlagueCZ** [comment]
@byteocean actually can you postpone for another of my PRs? Because in there there already is a pytest covering this in a centralized way, just commented out to make the runner work. I'll create an issue once it' ready.

**Comment by PlagueCZ** [comment]
Just one more PR please because that one brings new gRPC tests that test this situation in multiple ways and your new test would make a conflict.

**Comment by PlagueCZ** [comment]
@guvenc changed to be ready for the PR that changes test of gRPC and already tests these cases in a systematic way. This then should be merged first.

**Review by guvenc — APPROVED** [review]
Thanks.

**Pull request merged**
